fov:
  cup_0.5HZ: 55.0
  cup_0.9HZ: 55.0
  cup_1.1HZ: 55.0
  cup_1.5HZ: 55.0
  cup_1.8HZ: 55.0
  cup_2.1HZ: 55.0
  cup_3.2HZ: 55.0
  park_mavic_1: 66.0
  park_mavic_2: 66.0
  park_mavic_3: 66.0
  park_mavic_4: 66.0
  park_mavic_5: 66.0
  park_mavic_6: 66.0
  park_mavic_7: 66.0
  soccerfield_mavic_3: 66.0
  soccerfield_mavic_4: 66.0

ratio_thresh:
  KCF_hog: 0.1
  LDES_default: 0.3
  STRCF_default: 0.2
  CSRDCF_default: 0.2
  DIMP_dimp50: 0.5
  DIMP_prdimp50: 0.3
  KYS_default: 0.2
  TOMP_tomp101: 0.9
  MIXFORMER_vit: 0.98
  ECO_default: 0.5

interp_factor:
  KCF_hog: 
    cup_0.5HZ: 0
    cup_0.9HZ: 0
    cup_1.1HZ: 0
    cup_1.5HZ: 0
    cup_1.8HZ: 0
    cup_2.1HZ: 0
    cup_3.2HZ: 0
    park_mavic_1: 1
    park_mavic_2: 1
    park_mavic_3: 1
    park_mavic_4: 1
    park_mavic_5: 1
    park_mavic_6: 1
    park_mavic_7: 1
    soccerfield_mavic_3: 1
    soccerfield_mavic_4: 1
  LDES_default:
    cup_0.5HZ: 0
    cup_0.9HZ: 0
    cup_1.1HZ: 0
    cup_1.5HZ: 0
    cup_1.8HZ: 0
    cup_2.1HZ: 0
    cup_3.2HZ: 0
    park_mavic_1: 1
    park_mavic_2: 1
    park_mavic_3: 1
    park_mavic_4: 1
    park_mavic_5: 1
    park_mavic_6: 1
    park_mavic_7: 1
    soccerfield_mavic_3: 1
    soccerfield_mavic_4: 1
  STRCF_default:
    cup_0.5HZ: 0
    cup_0.9HZ: 0
    cup_1.1HZ: 0
    cup_1.5HZ: 0
    cup_1.8HZ: 0
    cup_2.1HZ: 0
    cup_3.2HZ: 0
    park_mavic_1: 1
    park_mavic_2: 1
    park_mavic_3: 1
    park_mavic_4: 1
    park_mavic_5: 1
    park_mavic_6: 1
    park_mavic_7: 1
    soccerfield_mavic_3: 1
    soccerfield_mavic_4: 1
  CSRDCF_default: 
    cup_0.5HZ: 0
    cup_0.9HZ: 0
    cup_1.1HZ: 0
    cup_1.5HZ: 0
    cup_1.8HZ: 0
    cup_2.1HZ: 0
    cup_3.2HZ: 0
    park_mavic_1: 1
    park_mavic_2: 1
    park_mavic_3: 1
    park_mavic_4: 1
    park_mavic_5: 1
    park_mavic_6: 1
    park_mavic_7: 1
    soccerfield_mavic_3: 1
    soccerfield_mavic_4: 1
  DIMP_dimp50:
    cup_0.5HZ: 1.1
    cup_0.9HZ: 1.1
    cup_1.1HZ: 1.1
    cup_1.5HZ: 1.1
    cup_1.8HZ: 1.1
    cup_2.1HZ: 1.1
    cup_3.2HZ: 1.1
    park_mavic_1: 1.1
    park_mavic_2: 1.1
    park_mavic_3: 1.1
    park_mavic_4: 1.1
    park_mavic_5: 1.1
    park_mavic_6: 1.1
    park_mavic_7: 1.1
    soccerfield_mavic_3: 1.1
    soccerfield_mavic_4: 1.1
  DIMP_prdimp50:
    cup_0.5HZ: 1
    cup_0.9HZ: 1
    cup_1.1HZ: 1
    cup_1.5HZ: 1
    cup_1.8HZ: 1
    cup_2.1HZ: 1
    cup_3.2HZ: 1
    park_mavic_1: 1
    park_mavic_2: 1
    park_mavic_3: 1
    park_mavic_4: 1
    park_mavic_5: 1
    park_mavic_6: 1
    park_mavic_7: 1
    soccerfield_mavic_3: 1
    soccerfield_mavic_4: 1
  KYS_default:
    cup_0.5HZ: 1.1
    cup_0.9HZ: 1.1
    cup_1.1HZ: 1.1
    cup_1.5HZ: 1.1
    cup_1.8HZ: 1.1
    cup_2.1HZ: 1.1
    cup_3.2HZ: 1.1
    park_mavic_1: 1.1
    park_mavic_2: 1.1
    park_mavic_3: 1.1
    park_mavic_4: 1.1
    park_mavic_5: 1.1
    park_mavic_6: 1.1
    park_mavic_7: 1.1
    soccerfield_mavic_3: 1.1
    soccerfield_mavic_4: 1.1
  TOMP_tomp101:
    cup_0.5HZ: 1
    cup_0.9HZ: 1
    cup_1.1HZ: 1
    cup_1.5HZ: 1
    cup_1.8HZ: 1
    cup_2.1HZ: 1
    cup_3.2HZ: 1
    park_mavic_1: 1
    park_mavic_2: 1
    park_mavic_3: 1
    park_mavic_4: 1
    park_mavic_5: 1
    park_mavic_6: 1
    park_mavic_7: 1
    soccerfield_mavic_3: 1
    soccerfield_mavic_4: 1
  MIXFORMER_vit:
    cup_0.5HZ: 0
    cup_0.9HZ: 0
    cup_1.1HZ: 0
    cup_1.5HZ: 0
    cup_1.8HZ: 0
    cup_2.1HZ: 0
    cup_3.2HZ: 0
    park_mavic_1: 1
    park_mavic_2: 1
    park_mavic_3: 1
    park_mavic_4: 1
    park_mavic_5: 1
    park_mavic_6: 1
    park_mavic_7: 1
    soccerfield_mavic_3: 1
    soccerfield_mavic_4: 1
  ECO_default:
    cup_0.5HZ: 0
    cup_0.9HZ: 0
    cup_1.1HZ: 0
    cup_1.5HZ: 0
    cup_1.8HZ: 0
    cup_2.1HZ: 0
    cup_3.2HZ: 0
    park_mavic_1: 1
    park_mavic_2: 1
    park_mavic_3: 1
    park_mavic_4: 1
    park_mavic_5: 1
    park_mavic_6: 1
    park_mavic_7: 1
    soccerfield_mavic_3: 1
    soccerfield_mavic_4: 1
